### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by ralphte** [g0tmi1k/os-scripts#10]
There is a dead link to a wallpaper on line 1015. Not a big issue just thought I would let you know.

By the way thanks for the script.  I like it a lot.

**Comment by g0tmi1k** [comment]
Thanks for the heads up, will have it fixed when its ported over to kali rolling.

**Comment by mpgough** [comment]
I have uploaded kali blue splat again here:  http://i.imgur.com/Gl5fDxc.png.

Also gnmap-parser is all lower case now.

**Comment by g0tmi1k** [comment]
@ralphte  Fixed it! Thanks for the heads up =).

@mpgough Yup, that also caught me out. Also fixed.
