### ISSUE TITLE
Rolling items

### ISSUE THREAD

**Issue by Brockway** [g0tmi1k/os-scripts#13]
A couple of notes while playing around:

- fresh install of rolling today is 4.3.0 kernel via uname -r, which cannot be found by apt-get during the install kernel headers section. However, if not using VMWareTools and using OpenVMTools this is irrelevant, the OpenVMTools gets the proper kernel info and build fine. Just odd.
- While testing to see why 4.3.0 was not being found/installed, I performed a dist-upgrade which today gets the default rolling distro to 4.4.0. However, the installer then bails out during Update OS from network repositories section because it finds 2 kernels
- There are redundant sections that add the right repos to /etc/apt/sources.list
- apt-get couldn't find a rolling version of shutter
- some little things like conky not being transparent is easy to fix

Great stuff and thanks

**Comment by g0tmi1k** [comment]
Script is for kali 2, not kali rolling.
Hasn't been updated yet.

**Comment by g0tmi1k** [comment]
Ive just updated it to kali rolling. All these issues should now be fixed.

**Comment by Brockway** [comment]
dynamite, and thanks. just curious, what was the earlier --rolling option about then?

**Comment by g0tmi1k** [comment]
It added kali rolling repos to kali 2 (didn't replace them - which was a mistake).
At first, everything was okay. However after a few months rolling soon started to become very different to kali 2 (it grew into its own OS).
As software got switched about/upgraded/different ways of doing things, my script needed to be updated to support it all.
