### ISSUE TITLE
switching desktop environment issue

### ISSUE THREAD

**Issue by Felix4A** [g0tmi1k/os-scripts#15]
After running kali-rolling.sh and rebooting, the default desktop environment is Xfce. Thought I perfer GNOME so I used `update-alternatives --config x-session-manager` and chose GNOME.
After logging out, turns out to be Xfce again. So I tried switch to GNOME when logging in manually, only GNOME on Wayland works, GNOME and GNOME Classic just go straight to Xfce.

It's that a bug or just I did something wrong?

**Comment by g0tmi1k** [comment]
Try deleting: `~/.xsession`
Source: https://github.com/g0tmi1k/os-scripts/blob/6d8de8e2824d8af297c67a2177d747d709fd37ad/kali-rolling.sh#L696

**Comment by gabemarshall** [comment]
.m

**Comment by g0tmi1k** [comment]
This was fixed in eaebb5801c8108295366066f928e6282526abf53, and there hasn't been any feedback to say otherwise.
Closing.
