### ISSUE TITLE
Kali - Rolling - VMWare Image, missing folder

### ISSUE THREAD

**Issue by cidevant** [g0tmi1k/os-scripts#16]
Hi, 

after downloading vmware image of latest kali (rolling) and running ```os-scripts/kali-running.sh``` script finished with several errors.

* Folder ```/usr/local/bin``` is missing.
fixed by running ```make -p /usr/local/bin``` and rerunning pieces of code ```os-scripts/kali-running.sh``` which failed

* Missing ```sass``` ruby gem
fixed by running ```gem install sass``` 

## DEBUG LOG

asciinema
```
 [+] (55/188) Installing asciinema ~ CLI terminal recorder
Downloading asciinema v1.2.0 for linux-amd64...
######################################################################## 100.0%
Warning: couldn't find ~/bin or /usr/local/bin in your $PATH
Installing to /tmp/os-scripts/asciinema...
Success.
```

graudit
```
 [+] (52/188) Installing graudit ~ source code auditing
git is already the newest version (1:2.8.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
./kali-rolling.sh: line 2074: /usr/local/bin/graudit-git: No such file or directory
 [!] Issue with writing file
chmod: cannot access '/usr/local/bin/graudit-git': No such file or directory
```

conky
```
Setting up conky (1.10.2-1) ...
./kali-rolling.sh: line 1616: /usr/local/bin/start-conky: No such file or directory
 [!] Issue with writing file
```

random wallpaper
```
./kali-rolling.sh: line 745: /usr/local/bin/rand-wallpaper: No such file or directory
 [!] Issue with writing file
bash: /usr/local/bin/rand-wallpaper: No such file or directory
```

update OS from network repositories
```
Setting up dradis (3.0.0~rc1-0kali1+b2) ...
/usr/lib/ruby/vendor_ruby/tilt/less.rb:2:in `require': cannot load such file -- less (LoadError)
    from /usr/lib/ruby/vendor_ruby/tilt/less.rb:2:in `<top (required)>'
    from /usr/lib/dradis/vendor/bundle/ruby/2.3.0/gems/sprockets-2.11.0/lib/sprockets.rb:101:in `require'
    from /usr/lib/dradis/vendor/bundle/ruby/2.3.0/gems/sprockets-2.11.0/lib/sprockets.rb:101:in `<module:Sprockets>'
    from /usr/lib/dradis/vendor/bundle/ruby/2.3.0/gems/sprockets-2.11.0/lib/sprockets.rb:3:in `<top (required)>'
    from /usr/lib/dradis/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.2.4/lib/sprockets/railtie.rb:5:in `require'
    from /usr/lib/dradis/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.2.4/lib/sprockets/railtie.rb:5:in `<top (required)>'
    from /usr/lib/dradis/config/application.rb:9:in `require'
    from /usr/lib/dradis/config/application.rb:9:in `<top (required)>'
    from /usr/lib/dradis/config/environment.rb:2:in `require'
```

**Comment by g0tmi1k** [comment]
Thanks for the heads up - I'll look into it next week ish.

**Comment by Brockway** [comment]
Seeing almost same issue here but my /usr/local/bin definitely exists pre-post-install script, the above same sections of the script give me the same errors, haven't been able to figure this one out

**Comment by g0tmi1k** [comment]
Thanks for the bug report!

I've added `mkdir -p /usr/local/bin/` in (because its used).
At this stage, I don't want to mess about with altering `$PATH` too much (especially as I don't seam to have this issue).

Based on what you have said, I'm not sure what `gem install sass` is meant to fix? Why not just install `less`?

...and I'm not touching `dradis` with a 10 foot pole ;) 
It's an issue with the kali package - and needs to be added to kali's bug tracker (https://bugs.kali.org/).

**Comment by cidevant** [comment]
`gem install sass` fixes error `/usr/lib/ruby/vendor_ruby/tilt/less.rb:2:in `require': cannot load such file -- less (LoadError)`

Less, Sass, Scss - is included in SASS ruby gem.

**Comment by g0tmi1k** [comment]
This then needs to be reported in the kali bug tracker (https://bugs.kali.org/) to get it fixed upstream.

**Comment by cidevant** [comment]
Its not the problem of kali. Kali has preinstalled ruby on it. But it misses SASS gem (gem is package, library, module). It could be solved by "gem install" program.

**Comment by g0tmi1k** [comment]
If dradis needs a gem to run - its a problem with the requirements of the package.

If doing `apt install dradis`, and then running dradis doesn't work - theres an issue with the package.
If you have to-do an extra step afterwards - there's an issue upstream.

**Comment by cidevant** [comment]
Ok, I agree with you!

**Comment by g0tmi1k** [comment]
Upstream bug report has been made: https://bugs.kali.org/view.php?id=3607
