### ISSUE TITLE
"Open terminal here" not working

### ISSUE THREAD

**Issue by cicaglisa** [g0tmi1k/os-scripts#18]
When right clicking and choosing Open terminal here inside of folder - it opens up a terminal with previous working directory.
The issue is noticed in Kali Rolling

**Comment by g0tmi1k** [comment]
Thanks for the bug report.
This was happening due to ZSH's plugin: `last-working-dir`.
Fixed the issue now.

File: `~/.zshrc`.

```
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zs    h/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(git git-extras tmux last-working-dir dirhistory p    ython pip)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras tmux last-working-dir dirhistory python pip)
```
