### ISSUE TITLE
sshulttle is removed from kali-rolling

### ISSUE THREAD

**Issue by Sinderella** [g0tmi1k/os-scripts#19]
Link to the tracker: http://pkg.kali.org/pkg/sshuttle

You probably want to fix this: https://github.com/g0tmi1k/os-scripts/blob/master/kali-rolling.sh#L2697

**Comment by Sinderella** [comment]
It's imported back.

**Comment by g0tmi1k** [comment]
Glad to see it fixed itself & thanks for the bug report!

Little worrying that it happened to start with - but that's "half the fun" with a rolling OS now...
