### ISSUE TITLE
Download failed for '90145-axiom.tar.gz'

### ISSUE THREAD

**Issue by fruchttiger00x0** [g0tmi1k/os-scripts#20]
Greetings g0tmi1k,

thanks for all the fresh updates so far, script is always first choice!

Just a 'curl' to rework but this one is a little showstopper. 
The theme download fail with a 403 forbidden but the script won't skip additional steps. Like line 707-709

So here we get a 403
https://github.com/g0tmi1k/os-scripts/blob/master/kali-rolling.sh#L705

And here's a little one which might do it
curl -O -J --progress -k -L -f 'https://www.ppload.com/api/files/download?id=1461767736' -H 'Referer: https://www.xfce-look.org/content/show.php/axiom+xfwm?content=90145' --compressed

Regards

**Comment by Brockway** [comment]
looks like a changed link, this looks to be working - https://dl.opendesktop.org/api/files/download/id/1461767736/90145-axiom.tar.gz

**Comment by g0tmi1k** [comment]
Thanks for the bug report!
Fixed in b970909a2a9e15df87ddd3ec5834e0fa01fdc12c.
