### ISSUE TITLE
Screensaver blacks out desktop

### ISSUE THREAD

**Issue by sheimo** [g0tmi1k/os-scripts#21]
After 10 minutes or so the screen blacks out, I'm assuming it's the screensaver and it won't return back to the desktop after moving mouse or pressing keys. Brand new install, then used post script. I can pop into ctrl+at f2 login, but can't recover f1 session.

**Comment by 0xdeafbeef** [comment]
Same issue, mine's in a fresh install under VirtualBox.

**Comment by Brockway** [comment]
Same. Settings>Power no longer exists after post script to adjust screen lockout setting, which is odd.

**Comment by FreedomShepherd** [comment]
same here.

**Comment by Brockway** [comment]
Ha, spent a few hours today writing script that installs xfce4-power-manager from sources :) Can run xfce4-power-manager-settings to get the settings window. I didn't kill light-locker, it is still running but is not locking.

**Comment by g0tmi1k** [comment]
Thanks for the bug report guys and steps to fix it.
I've got ahead and automated it with commit: 102f114db0ca800f6b586a77ba084db7e22be031
