### ISSUE TITLE
Kali 2016.2 rand-wallpaper no longer works

### ISSUE THREAD

**Issue by Brockway** [g0tmi1k/os-scripts#25]
kali-rolling script, rand-wallpaper/xfdesktop --reload is not actually changing the wallpaper. The files are getting assigned correctly (verified by xfconf-query) but reload does nothing.

**Comment by g0tmi1k** [comment]
Thanks for the bug report!
Looks like something is now different...

Old way: `/backdrop/screen0/monitor0/image-path`
New way: `/backdrop/screen0/monitor0/workspace0/last-image`
