### ISSUE TITLE
Issues for me running this script: Get the Failed to kill /usr/lib/apt/methods/http

### ISSUE THREAD

**Issue by supertweak** [g0tmi1k/os-scripts#5]

**Comment by houey** [comment]
there are two lock files you need to rm

**Comment by houey** [comment]
rm /var/lib/dpkg/lock
rm /var/lib/apt/lists/lock

**Comment by supertweak** [comment]
Awesome, thanks for the help. That fixed my issue.

**Comment by g0tmi1k** [comment]
For the record, commit cd2f2079a3c08a9a1d07c8a7af5ae416ea53d66d should help out here!
Sorry for any issues.
